# Generated by Django 4.2.3 on 2023-08-19 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_userprofile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_staff',
        ),
    ]
