# Generated by Django 4.2.3 on 2023-08-17 15:33

import django.core.validators
from django.db import migrations, models
import exam_store.main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='name',
            field=models.CharField(max_length=100, validators=[exam_store.main.validators.validate_starts_with_uppercase, django.core.validators.MinLengthValidator(3)]),
        ),
    ]
