# Generated by Django 4.2.3 on 2023-08-17 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_productmodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='category',
            field=models.CharField(choices=[('shoes', 'Shoes'), ('clothes', 'Clothes'), ('accessories', 'Accessories')], max_length=20),
        ),
        migrations.DeleteModel(
            name='CategoryModel',
        ),
    ]
